[build]
builder = "nixpacks"

[build.nixpacks.phases.setup]
aptPkgs = ["curl", "gcc", "g++"]

[build.nixpacks.phases.install]
cmds = [
  "cd src && npm ci",
  "pip install -r requirements.txt"
]

[build.nixpacks.phases.build]
cmds = [
  "cd src && npm run build"
]

[deploy]
startCommand = "python run.py"
restartPolicyType = "on-failure"

[deploy.healthcheckPath]
value = "/api/health"
