[build]
builder = "dockerfile"

[build.buildCommand]
value = "echo 'Building with Docker multi-stage...'"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:8080 --workers 2 --threads 4 --timeout 120 wsgi:app"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[deploy.healthcheckPath]
value = "/api/health"

[deploy.healthcheckTimeout]
value = 30

[environments.production]
variables = {}

[environments.development]
variables = {}
