[build]
builder = "nixpacks" 

[build.buildCommand]
value = "cd src && npm install && npm run build && cd .. && pip install -r requirements.txt"

[deploy]
startCommand = "python run.py"

[deploy.healthcheckPath] 
value = "/api/health"
