[build]
builder = "nixpacks"

[build.buildCommand]
value = "cd src && npm ci && npm run build && cd .. && pip install -r requirements.txt"

[deploy]
startCommand = "python run.py"
restartPolicyType = "on-failure"

[deploy.healthcheckPath]
value = "/api/health"
